apiVersion: v1
kind: Namespace
metadata:
  name: malgoof
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: malgoof
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: malgoof
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: malgoof
subjects:
- kind: ServiceAccount
  name: default
  namespace: malgoof
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
