master:
  image: "jenkins/jenkins"
  imageTag: "2.197-alpine"
  adminUser: admin
  # AdminPassword: <defaults to random>
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "8Gi"
  JavaOpts: "-Duser.timezone=America/New_York"
  # JavaOpts: "-Xms512m -Xmx512m" - Configure default heap size limits to match resource claims
  # JenkinsOpts: ""
  serviceType: NodePort # Use ClusterIP to use the ingress controller.
  installPlugins:
    - kubernetes:1.19.2
    - workflow-job:2.35
    - workflow-aggregator:2.6
    - credentials-binding:1.20
    - role-strategy:2.14
    - github:1.29.4
    - github-oauth:0.33
    - git:3.12.1
    - blueocean:1.19.0
    - rocketchatnotifier:1.4.5
    - ws-cleanup:0.37
    - pipeline-utility-steps:2.3.1
    - ldap:1.20
    - matrix-auth:2.4.2
  ingress:
    enabled: false
    hostName: your.name.tld
    annotations:
      kubernetes.io/ingress.class: "default" # You will need to use the appropriate class for your cluster.
    tls:
    - hosts:
      - your.name.tld
     # secretName: your-tls-cert

agent:
  enabled: true
  image: jenkins/jnlp-slave
  #ImageTag: 3.27-1
  alwaysPullImage: false # Set to "true" if using a tag like "latest" that tracks changing versions
  resources:
    requests:
      cpu: "0.5"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "2Gi"

persistence:
  enabled: false # Set to true to persist across tests
  #existingClaim: "your-pvc"

rbac:
  create: false

serviceAccount:
  create: false
